//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EasyfattDocuments {
    
    private CompanyType companyField;
    
    private DocumentType[] documentsField;
    
    private int appVersionField;
    
    private bool appVersionFieldSpecified;
    
    private string creatorField;
    
    private string creatorUrlField;
    
    /// <remarks/>
    public CompanyType Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
    public DocumentType[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int AppVersion {
        get {
            return this.appVersionField;
        }
        set {
            this.appVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AppVersionSpecified {
        get {
            return this.appVersionFieldSpecified;
        }
        set {
            this.appVersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Creator {
        get {
            return this.creatorField;
        }
        set {
            this.creatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CreatorUrl {
        get {
            return this.creatorUrlField;
        }
        set {
            this.creatorUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CompanyType {
    
    private string nameField;
    
    private string addressField;
    
    private string postcodeField;
    
    private string cityField;
    
    private string provinceField;
    
    private string countryField;
    
    private string fiscalCodeField;
    
    private string vatCodeField;
    
    private string telField;
    
    private string faxField;
    
    private string emailField;
    
    private string homePageField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string Postcode {
        get {
            return this.postcodeField;
        }
        set {
            this.postcodeField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string FiscalCode {
        get {
            return this.fiscalCodeField;
        }
        set {
            this.fiscalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string VatCode {
        get {
            return this.vatCodeField;
        }
        set {
            this.vatCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Tel {
        get {
            return this.telField;
        }
        set {
            this.telField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string HomePage {
        get {
            return this.homePageField;
        }
        set {
            this.homePageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PaymentType {
    
    private bool advanceField;
    
    private bool advanceFieldSpecified;
    
    private System.DateTime dateField;
    
    private decimal amountField;
    
    private bool paidField;
    
    private bool paidFieldSpecified;
    
    /// <remarks/>
    public bool Advance {
        get {
            return this.advanceField;
        }
        set {
            this.advanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdvanceSpecified {
        get {
            return this.advanceFieldSpecified;
        }
        set {
            this.advanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public bool Paid {
        get {
            return this.paidField;
        }
        set {
            this.paidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaidSpecified {
        get {
            return this.paidFieldSpecified;
        }
        set {
            this.paidFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RowType {
    
    private string codeField;
    
    private string supplierCodeField;
    
    private string descriptionField;
    
    private decimal qtyField;
    
    private string umField;
    
    private string sizeField;
    
    private string colorField;
    
    private string lotField;
    
    private System.DateTime expiryDateField;
    
    private string serialField;
    
    private decimal priceField;
    
    private string discountsField;
    
    private decimal ecoFeeField;
    
    private RowTypeVatCode vatCodeField;
    
    private decimal totalField;
    
    private bool withholdingTaxField;
    
    private bool withholdingTaxFieldSpecified;
    
    private bool stockField;
    
    private bool stockFieldSpecified;
    
    private decimal commissionPercField;
    
    private string notesField;
    
    public RowType() {
        this.qtyField = ((decimal)(0m));
        this.expiryDateField = new System.DateTime(946391904000000000);
        this.priceField = ((decimal)(0m));
        this.ecoFeeField = ((decimal)(0m));
        this.totalField = ((decimal)(0m));
        this.commissionPercField = ((decimal)(0m));
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierCode {
        get {
            return this.supplierCodeField;
        }
        set {
            this.supplierCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
    
    /// <remarks/>
    public string Um {
        get {
            return this.umField;
        }
        set {
            this.umField = value;
        }
    }
    
    /// <remarks/>
    public string Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    public string Lot {
        get {
            return this.lotField;
        }
        set {
            this.lotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "2999-12-31")]
    public System.DateTime ExpiryDate {
        get {
            return this.expiryDateField;
        }
        set {
            this.expiryDateField = value;
        }
    }
    
    /// <remarks/>
    public string Serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string Discounts {
        get {
            return this.discountsField;
        }
        set {
            this.discountsField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal EcoFee {
        get {
            return this.ecoFeeField;
        }
        set {
            this.ecoFeeField = value;
        }
    }
    
    /// <remarks/>
    public RowTypeVatCode VatCode {
        get {
            return this.vatCodeField;
        }
        set {
            this.vatCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    public bool WithholdingTax {
        get {
            return this.withholdingTaxField;
        }
        set {
            this.withholdingTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WithholdingTaxSpecified {
        get {
            return this.withholdingTaxFieldSpecified;
        }
        set {
            this.withholdingTaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool Stock {
        get {
            return this.stockField;
        }
        set {
            this.stockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StockSpecified {
        get {
            return this.stockFieldSpecified;
        }
        set {
            this.stockFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal CommissionPerc {
        get {
            return this.commissionPercField;
        }
        set {
            this.commissionPercField = value;
        }
    }
    
    /// <remarks/>
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RowTypeVatCode {
    
    private decimal percField;
    
    private bool percFieldSpecified;
    
    private string classField;
    
    private string descriptionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Perc {
        get {
            return this.percField;
        }
        set {
            this.percField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PercSpecified {
        get {
            return this.percFieldSpecified;
        }
        set {
            this.percFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentType {
    
    private DocumentTypeDocumentType documentType1Field;
    
    private System.DateTime dateField;
    
    private int numberField;
    
    private bool numberFieldSpecified;
    
    private string numberingField;
    
    private string customerNameField;
    
    private string customerCodeField;
    
    private string customerWebLoginField;
    
    private string customerAddressField;
    
    private string customerPostcodeField;
    
    private string customerCityField;
    
    private string customerProvinceField;
    
    private string customerCountryField;
    
    private string customerFiscalCodeField;
    
    private string customerVatCodeField;
    
    private string customerReferenceField;
    
    private string customerTelField;
    
    private string customerCellPhoneField;
    
    private string customerFaxField;
    
    private string customerEmailField;
    
    private string customerPecField;
    
    private string deliveryNameField;
    
    private string deliveryAddressField;
    
    private string deliveryPostcodeField;
    
    private string deliveryCityField;
    
    private string deliveryProvinceField;
    
    private string deliveryCountryField;
    
    private string warehouseField;
    
    private string costDescriptionField;
    
    private DocumentTypeCostVatCode costVatCodeField;
    
    private decimal costAmountField;
    
    private decimal totalWithoutTaxField;
    
    private decimal vatAmountField;
    
    private decimal withholdingTaxAmountField;
    
    private decimal withholdingTaxAmountBField;
    
    private decimal totalField;
    
    private string priceListField;
    
    private bool pricesIncludeVatField;
    
    private bool pricesIncludeVatFieldSpecified;
    
    private decimal withholdingTaxPercField;
    
    private decimal withholdingTaxPerc2Field;
    
    private string withholdingTaxNameBField;
    
    private string contribDescriptionField;
    
    private decimal contribPercField;
    
    private System.Nullable<bool> contribSubjectToWithholdingTaxField;
    
    private decimal contribAmountField;
    
    private decimal contribVatCodeField;
    
    private string paymentNameField;
    
    private string paymentBankField;
    
    private string customField1Field;
    
    private string customField2Field;
    
    private string customField3Field;
    
    private string customField4Field;
    
    private string footNotesField;
    
    private string salesAgentField;
    
    private bool delayedVatField;
    
    private bool delayedVatFieldSpecified;
    
    private string delayedVatDescField;
    
    private bool delayedVatDueWithinOneYearField;
    
    private bool delayedVatDueWithinOneYearFieldSpecified;
    
    private decimal paymentAdvanceAmountField;
    
    private string carrierField;
    
    private string transportReasonField;
    
    private string goodsAppearanceField;
    
    private string transportDateTimeField;
    
    private string shipmentTermsField;
    
    private double transportedWeightField;
    
    private string trackingNumberField;
    
    private string internalCommentField;
    
    private System.Nullable<int> numOfPiecesField;
    
    private System.DateTime expectedConclusionDateField;
    
    private string docReferenceField;
    
    private RowType[] rowsField;
    
    private PaymentType[] paymentsField;
    
    private DocumentTypePdf pdfField;
    
    public DocumentType() {
        this.documentType1Field = DocumentTypeDocumentType.C;
        this.costAmountField = ((decimal)(0m));
        this.totalWithoutTaxField = ((decimal)(0m));
        this.vatAmountField = ((decimal)(0m));
        this.withholdingTaxAmountField = ((decimal)(0m));
        this.withholdingTaxAmountBField = ((decimal)(0m));
        this.withholdingTaxPercField = ((decimal)(0m));
        this.withholdingTaxPerc2Field = ((decimal)(0m));
        this.contribPercField = ((decimal)(0m));
        this.contribSubjectToWithholdingTaxField = false;
        this.contribAmountField = ((decimal)(0m));
        this.contribVatCodeField = ((decimal)(0m));
        this.paymentAdvanceAmountField = ((decimal)(0m));
        this.transportedWeightField = 0D;
        this.numOfPiecesField = 0;
        this.expectedConclusionDateField = new System.DateTime(946391904000000000);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentType")]
    public DocumentTypeDocumentType DocumentType1 {
        get {
            return this.documentType1Field;
        }
        set {
            this.documentType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public int Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberSpecified {
        get {
            return this.numberFieldSpecified;
        }
        set {
            this.numberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Numbering {
        get {
            return this.numberingField;
        }
        set {
            this.numberingField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerCode {
        get {
            return this.customerCodeField;
        }
        set {
            this.customerCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerWebLogin {
        get {
            return this.customerWebLoginField;
        }
        set {
            this.customerWebLoginField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerPostcode {
        get {
            return this.customerPostcodeField;
        }
        set {
            this.customerPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerCity {
        get {
            return this.customerCityField;
        }
        set {
            this.customerCityField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerProvince {
        get {
            return this.customerProvinceField;
        }
        set {
            this.customerProvinceField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerCountry {
        get {
            return this.customerCountryField;
        }
        set {
            this.customerCountryField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerFiscalCode {
        get {
            return this.customerFiscalCodeField;
        }
        set {
            this.customerFiscalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerVatCode {
        get {
            return this.customerVatCodeField;
        }
        set {
            this.customerVatCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerReference {
        get {
            return this.customerReferenceField;
        }
        set {
            this.customerReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerTel {
        get {
            return this.customerTelField;
        }
        set {
            this.customerTelField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerCellPhone {
        get {
            return this.customerCellPhoneField;
        }
        set {
            this.customerCellPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerFax {
        get {
            return this.customerFaxField;
        }
        set {
            this.customerFaxField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerEmail {
        get {
            return this.customerEmailField;
        }
        set {
            this.customerEmailField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerPec {
        get {
            return this.customerPecField;
        }
        set {
            this.customerPecField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryName {
        get {
            return this.deliveryNameField;
        }
        set {
            this.deliveryNameField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryAddress {
        get {
            return this.deliveryAddressField;
        }
        set {
            this.deliveryAddressField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryPostcode {
        get {
            return this.deliveryPostcodeField;
        }
        set {
            this.deliveryPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryCity {
        get {
            return this.deliveryCityField;
        }
        set {
            this.deliveryCityField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryProvince {
        get {
            return this.deliveryProvinceField;
        }
        set {
            this.deliveryProvinceField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryCountry {
        get {
            return this.deliveryCountryField;
        }
        set {
            this.deliveryCountryField = value;
        }
    }
    
    /// <remarks/>
    public string Warehouse {
        get {
            return this.warehouseField;
        }
        set {
            this.warehouseField = value;
        }
    }
    
    /// <remarks/>
    public string CostDescription {
        get {
            return this.costDescriptionField;
        }
        set {
            this.costDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public DocumentTypeCostVatCode CostVatCode {
        get {
            return this.costVatCodeField;
        }
        set {
            this.costVatCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal CostAmount {
        get {
            return this.costAmountField;
        }
        set {
            this.costAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal TotalWithoutTax {
        get {
            return this.totalWithoutTaxField;
        }
        set {
            this.totalWithoutTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal VatAmount {
        get {
            return this.vatAmountField;
        }
        set {
            this.vatAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal WithholdingTaxAmount {
        get {
            return this.withholdingTaxAmountField;
        }
        set {
            this.withholdingTaxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal WithholdingTaxAmountB {
        get {
            return this.withholdingTaxAmountBField;
        }
        set {
            this.withholdingTaxAmountBField = value;
        }
    }
    
    /// <remarks/>
    public decimal Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    public string PriceList {
        get {
            return this.priceListField;
        }
        set {
            this.priceListField = value;
        }
    }
    
    /// <remarks/>
    public bool PricesIncludeVat {
        get {
            return this.pricesIncludeVatField;
        }
        set {
            this.pricesIncludeVatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PricesIncludeVatSpecified {
        get {
            return this.pricesIncludeVatFieldSpecified;
        }
        set {
            this.pricesIncludeVatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal WithholdingTaxPerc {
        get {
            return this.withholdingTaxPercField;
        }
        set {
            this.withholdingTaxPercField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal WithholdingTaxPerc2 {
        get {
            return this.withholdingTaxPerc2Field;
        }
        set {
            this.withholdingTaxPerc2Field = value;
        }
    }
    
    /// <remarks/>
    public string WithholdingTaxNameB {
        get {
            return this.withholdingTaxNameBField;
        }
        set {
            this.withholdingTaxNameBField = value;
        }
    }
    
    /// <remarks/>
    public string ContribDescription {
        get {
            return this.contribDescriptionField;
        }
        set {
            this.contribDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal ContribPerc {
        get {
            return this.contribPercField;
        }
        set {
            this.contribPercField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public System.Nullable<bool> ContribSubjectToWithholdingTax {
        get {
            return this.contribSubjectToWithholdingTaxField;
        }
        set {
            this.contribSubjectToWithholdingTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal ContribAmount {
        get {
            return this.contribAmountField;
        }
        set {
            this.contribAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal ContribVatCode {
        get {
            return this.contribVatCodeField;
        }
        set {
            this.contribVatCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentName {
        get {
            return this.paymentNameField;
        }
        set {
            this.paymentNameField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentBank {
        get {
            return this.paymentBankField;
        }
        set {
            this.paymentBankField = value;
        }
    }
    
    /// <remarks/>
    public string CustomField1 {
        get {
            return this.customField1Field;
        }
        set {
            this.customField1Field = value;
        }
    }
    
    /// <remarks/>
    public string CustomField2 {
        get {
            return this.customField2Field;
        }
        set {
            this.customField2Field = value;
        }
    }
    
    /// <remarks/>
    public string CustomField3 {
        get {
            return this.customField3Field;
        }
        set {
            this.customField3Field = value;
        }
    }
    
    /// <remarks/>
    public string CustomField4 {
        get {
            return this.customField4Field;
        }
        set {
            this.customField4Field = value;
        }
    }
    
    /// <remarks/>
    public string FootNotes {
        get {
            return this.footNotesField;
        }
        set {
            this.footNotesField = value;
        }
    }
    
    /// <remarks/>
    public string SalesAgent {
        get {
            return this.salesAgentField;
        }
        set {
            this.salesAgentField = value;
        }
    }
    
    /// <remarks/>
    public bool DelayedVat {
        get {
            return this.delayedVatField;
        }
        set {
            this.delayedVatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DelayedVatSpecified {
        get {
            return this.delayedVatFieldSpecified;
        }
        set {
            this.delayedVatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string DelayedVatDesc {
        get {
            return this.delayedVatDescField;
        }
        set {
            this.delayedVatDescField = value;
        }
    }
    
    /// <remarks/>
    public bool DelayedVatDueWithinOneYear {
        get {
            return this.delayedVatDueWithinOneYearField;
        }
        set {
            this.delayedVatDueWithinOneYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DelayedVatDueWithinOneYearSpecified {
        get {
            return this.delayedVatDueWithinOneYearFieldSpecified;
        }
        set {
            this.delayedVatDueWithinOneYearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
    public decimal PaymentAdvanceAmount {
        get {
            return this.paymentAdvanceAmountField;
        }
        set {
            this.paymentAdvanceAmountField = value;
        }
    }
    
    /// <remarks/>
    public string Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    public string TransportReason {
        get {
            return this.transportReasonField;
        }
        set {
            this.transportReasonField = value;
        }
    }
    
    /// <remarks/>
    public string GoodsAppearance {
        get {
            return this.goodsAppearanceField;
        }
        set {
            this.goodsAppearanceField = value;
        }
    }
    
    /// <remarks/>
    public string TransportDateTime {
        get {
            return this.transportDateTimeField;
        }
        set {
            this.transportDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string ShipmentTerms {
        get {
            return this.shipmentTermsField;
        }
        set {
            this.shipmentTermsField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double TransportedWeight {
        get {
            return this.transportedWeightField;
        }
        set {
            this.transportedWeightField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string InternalComment {
        get {
            return this.internalCommentField;
        }
        set {
            this.internalCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public System.Nullable<int> NumOfPieces {
        get {
            return this.numOfPiecesField;
        }
        set {
            this.numOfPiecesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "2999-12-31")]
    public System.DateTime ExpectedConclusionDate {
        get {
            return this.expectedConclusionDateField;
        }
        set {
            this.expectedConclusionDateField = value;
        }
    }
    
    /// <remarks/>
    public string DocReference {
        get {
            return this.docReferenceField;
        }
        set {
            this.docReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Row", IsNullable=false)]
    public RowType[] Rows {
        get {
            return this.rowsField;
        }
        set {
            this.rowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Payment", IsNullable=false)]
    public PaymentType[] Payments {
        get {
            return this.paymentsField;
        }
        set {
            this.paymentsField = value;
        }
    }
    
    /// <remarks/>
    public DocumentTypePdf Pdf {
        get {
            return this.pdfField;
        }
        set {
            this.pdfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DocumentTypeDocumentType {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    L,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    P,
    
    /// <remarks/>
    Q,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    H,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentTypeCostVatCode {
    
    private decimal percField;
    
    private bool percFieldSpecified;
    
    private string classField;
    
    private string descriptionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Perc {
        get {
            return this.percField;
        }
        set {
            this.percField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PercSpecified {
        get {
            return this.percFieldSpecified;
        }
        set {
            this.percFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DocumentTypePdf {
    
    private string fileNameField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
